const { nowISO } = require("./dates");

function createId(prefix) {
  return `${prefix}_${Math.random().toString(16).slice(2, 10)}${Date.now().toString(16).slice(-6)}`;
}

function createSeedData() {
  return {
    tokens: {},
    sessions: [],
    idempotency: {},
    users: [],
    profiles: [],
    leadProfiles: [],
    identityLinks: [],
    youzanOrders: [
      {
        order_id: "ord_root_001",
        user_id: "",
        youzan_order_no: "YZROOT202604260001",
        phone: "13800000001",
        receiver_name: "王小路",
        receiver_phone: "13800000001",
        product_name: "ROOT 7日试饮装",
        product_id: "ROOT-PREBIOTIC-TRIAL",
        amount: 199,
        paid_at: "2026-04-26T10:12:00+08:00",
        order_status: "PAID",
        delivery_status: "DELIVERED",
        raw_address_text: "上海市演示地址1号",
        matched_at: "",
        match_source: "",
      },
      {
        order_id: "ord_root_002",
        user_id: "",
        youzan_order_no: "YZROOT202604260002",
        phone: "13800000002",
        receiver_name: "李小根",
        receiver_phone: "13800000002",
        product_name: "ROOT 7日试饮装",
        product_id: "ROOT-PREBIOTIC-TRIAL",
        amount: 199,
        paid_at: "2026-04-26T11:20:00+08:00",
        order_status: "PAID",
        delivery_status: "SHIPPED",
        raw_address_text: "杭州市演示地址2号",
        matched_at: "",
        match_source: "",
      },
      {
        order_id: "ord_root_used",
        user_id: "usr_finished",
        youzan_order_no: "YZROOT202604200099",
        phone: "13800000099",
        receiver_name: "陈已用",
        receiver_phone: "13800000099",
        product_name: "ROOT 7日试饮装",
        product_id: "ROOT-PREBIOTIC-TRIAL",
        amount: 199,
        paid_at: "2026-04-20T09:00:00+08:00",
        order_status: "PAID",
        delivery_status: "DELIVERED",
        raw_address_text: "北京市演示地址99号",
        matched_at: "2026-04-20T09:00:00+08:00",
        match_source: "AUTO_PHONE",
      },
    ],
    orderFulfillments: [
      {
        fulfillment_id: "ful_ord_root_001",
        order_id: "ord_root_001",
        receiver_name: "王小路",
        receiver_phone: "13800000001",
        carrier: "SF",
        tracking_no: "SFROOT0001",
        delivery_status: "DELIVERED",
        shipped_at: "2026-04-26T14:00:00+08:00",
        delivered_at: "2026-04-28T10:30:00+08:00",
        last_event_text: "已签收",
        updated_at: nowISO(),
      },
      {
        fulfillment_id: "ful_ord_root_002",
        order_id: "ord_root_002",
        receiver_name: "李小根",
        receiver_phone: "13800000002",
        carrier: "YTO",
        tracking_no: "YTOROOT0002",
        delivery_status: "SHIPPED",
        shipped_at: "2026-04-26T15:20:00+08:00",
        delivered_at: "",
        last_event_text: "运输中",
        updated_at: nowISO(),
      },
      {
        fulfillment_id: "ful_ord_root_used",
        order_id: "ord_root_used",
        receiver_name: "陈已用",
        receiver_phone: "13800000099",
        carrier: "SF",
        tracking_no: "SFROOT0099",
        delivery_status: "DELIVERED",
        shipped_at: "2026-04-20T11:00:00+08:00",
        delivered_at: "2026-04-22T16:20:00+08:00",
        last_event_text: "已签收",
        updated_at: nowISO(),
      },
    ],
    operationTasks: [],
    dailySummaries: [],
    externalSampleReviews: [],
    importBatches: [],
    externalStatusMappings: [],
    auditLogs: [],
    externalAdapterRuns: [],
    externalAdapterCursors: [],
    couponEvents: [],
    questionnaireDefinitions: [],
    questionnaireResponses: [],
    refundWorkItems: [],
    checkinSessions: [],
    checkinRecords: [],
    dailyCheckinRecords: [],
    refunds: [],
    eventsTrack: [],
    uploads: [],
    events: [
      {
        event_id: createId("evt"),
        type: "seed_loaded",
        message: "ROOT demo data initialized",
        created_at: nowISO(),
      },
    ],
  };
}

module.exports = {
  createId,
  createSeedData,
};
